# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0002_item_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name=b'Pre\xc3\xa7o Unit\xc3\xa1rio'),
        ),
    ]
