# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0003_item_preco_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_unit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Pre\xc3\xa7o Unit\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name=b'Quantidade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_item',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Total'),
        ),
    ]
