# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0004_auto_20160121_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Pre\xc3\xa7o Unit\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Total'),
        ),
    ]
